<html>
  <head>
    <title>@yield('title')</title>
    <style>
      body{
        font-size:16pt;
        background-color:#99FFFF;
      }
    </style>
  </head>
  <body>
    @yield('content')
  </body>
</html>